/* 
 * runtimeTemplateEVM.js - EVM JavaScript Code Generator (FIXED VERSION)
 * Target: ESP32 EVM Runtime with @native.lvgl module
 * Fixed issues based on actual EVM API
 */

import { color_convert } from './runtimeWrapper.js';

// ==================== توابع اصلی ====================
export const template_evm_create = (id, parent_id, type) => {
    return `var ${id} = lv.${getEVMCreateFunction(type)}(${parent_id});`;
}

export const template_evm_setter_simple = (id, type, attr, param) => {
    const setterFunc = getEVMSetterFunction(type, attr);
    const formattedValue = formatEVMValue(attr, param);
    return `lv.${setterFunc}(${id}, ${formattedValue});`;
}

export const template_evm_api_simple = (id, type, api, param, par_id) => {
    if (id.startsWith('img') && (api === "set_src")) {
        return template_evm_img_api(id, type, api, param, par_id);
    }
    
    const formattedValue = formatEVMValue(api, param);
    const funcName = getEVMApiFunction(type, api);
    return `lv.${funcName}(${id}, ${formattedValue});`;
}

export const template_evm_img_api = (id, type, api, param, par_id) => {
    let paramskey = param.replace(/[ \.]/g, '_');
    return `    lv.lv_img_set_src(${id}, "${paramskey}");`;
}

export const template_evm_cb = (id) => {
    return `
// Event handler for ${id}
function ${id}_event_handler(obj, event_code) {
    if (event_code === lv.LV_EVENT_CLICKED) {
        // Add your click handling code here
    }
}`;
}

export const template_evm_all = (body, cb, actFileName) => {
    return `// ${actFileName}.js - Generated by LVGL Builder for EVM Runtime
// Target: ESP32 / Home Automation IoT
// EVM Version: 2.0 (QuickJS compatible)

var lv = require('@native.lvgl');
var styleModule = require('@native.lv_style');

/**********************
 *   EVENT HANDLERS
 **********************/
${cb}
/**********************
 *   MAIN UI FUNCTION
 **********************/
${body}

// Auto-execute the UI function
lvgl_lv_${actFileName}();`;
}

export const template_evm_styles = (node) => {
    let id = node.id;
    let type = node.type;
    
    let code = [];
    let hasStyle = false;
    
    // فقط propertyهای ایمن و تست شده
    const SAFE_PROPERTIES = {
        'bg_color': true,
        'bg_opa': true,
        'radius': true,
        'text_color': true,
        'border_color': true,
        'border_width': true,
        'arc_color': type === 'arc',
        'arc_width': type === 'arc'
    };
    
    for (let api of node.styles) {
        let api2 = api.split('.');
        let part = api2[0];
        let key = api2.length === 2 ? api2[1] : api;
        
        // فقط propertyهای ایمن
        if (SAFE_PROPERTIES[key]) {
            let param = node.data[api];
            if (param !== undefined && param !== null && param !== '') {
                if (!hasStyle) {
                    code.push(``);
                    hasStyle = true;
                }
                
                const formattedValue = formatEVMStyleValue(key, param);
                
                // برای آرک: arc_color و arc_width مستقیماً روی widget
                if (type === 'arc' && (key === 'arc_color' || key === 'arc_width')) {
                    code.push(`    styleModule.set_style_${key}(${id}, ${formattedValue});`);
                } 
                // برای سایر ویجت‌ها: bg_color, text_color, etc.
                else if (SAFE_PROPERTIES[key] === true) {
                    code.push(`    styleModule.set_style_${key}(${id}, ${formattedValue});`);
                }
            }
        }
    }
    
    return code.join('\n');
}

// ==================== توابع کمکی ====================
function getEVMCreateFunction(type) {
    const typeMap = {
        'obj': 'lv_obj_create',
        'btn': 'lv_btn_create',
        'label': 'lv_label_create',
        'arc': 'lv_arc_create',
        'img': 'lv_img_create',
        'slider': 'lv_slider_create',
        'switch': 'lv_switch_create',
        'checkbox': 'lv_checkbox_create',
        'textarea': 'lv_textarea_create',
        'dropdown': 'lv_dropdown_create',
    };
    return typeMap[type] || 'lv_obj_create';
}

function getEVMSetterFunction(type, attr) {
    const generalSetters = {
        'x': 'lv_obj_set_x',
        'y': 'lv_obj_set_y',
        'pos': 'lv_obj_set_pos',
        'width': 'lv_obj_set_width',
        'height': 'lv_obj_set_height',
        'size': 'lv_obj_set_size',
    };
    
    if (generalSetters[attr]) {
        return generalSetters[attr];
    }
    
    return `lv_${type}_set_${attr}`;
}

function getEVMApiFunction(type, api) {
    const specialAPIs = {
        'label': {
            'set_text': 'lv_label_set_text',
        },
        'btn': {
            'set_text': 'lv_btn_set_text',
        },
        'arc': {
            'set_value': 'lv_arc_set_value',
            'set_range': 'lv_arc_set_range',
            'set_start_angle': 'lv_arc_set_start_angle',
            'set_end_angle': 'lv_arc_set_end_angle',
            'set_bg_start_angle': 'lv_arc_set_bg_start_angle',
            'set_bg_end_angle': 'lv_arc_set_bg_end_angle',
            'set_mode': 'lv_arc_set_mode',
        },
        'slider': {
            'set_value': 'lv_slider_set_value',
        },
        'checkbox': {
            'set_text': 'lv_checkbox_set_text',
        },
        'textarea': {
            'set_text': 'lv_textarea_set_text',
        },
        'dropdown': {
            'set_options': 'lv_dropdown_set_options',
        },
        'img': {
            'set_src': 'lv_img_set_src',
            'set_angle': 'lv_img_set_angle',
        }
    };
    
    if (specialAPIs[type] && specialAPIs[type][api]) {
        return specialAPIs[type][api];
    }
    
    return `lv_${type}_${api}`;
}

// ==================== فرمت‌بندی ====================
function formatEVMValue(attr, value) {
    if (value === undefined || value === null || value === '') {
        return 'null';
    }
    
    // اگر رشته است
    if (typeof value === 'string') {
        let cleanValue = value;
        if (cleanValue.startsWith('"') && cleanValue.endsWith('"')) {
            cleanValue = cleanValue.slice(1, -1);
        }
        if (cleanValue.startsWith("'") && cleanValue.endsWith("'")) {
            cleanValue = cleanValue.slice(1, -1);
        }
        
        // اگر متن است
        if (attr === 'text' || attr.includes('text') || attr === 'src' || attr === 'options') {
            return `"${cleanValue}"`;
        }
        
        // اگر عدد است
        if (!isNaN(cleanValue) && cleanValue.trim() !== '') {
            return cleanValue;
        }
        
        // اگر boolean است (با حروف کوچک)
        if (cleanValue.toLowerCase() === 'false') return 'false';
        if (cleanValue.toLowerCase() === 'true') return 'true';
        
        return `"${cleanValue}"`;
    }
    
    // اگر عدد است
    if (typeof value === 'number') {
        // اگر رنگ است
        if (attr.includes('color')) {
            return `lv.lv_color_hex(0x${value.toString(16).padStart(6, '0')})`;
        }
        return value;
    }
    
    // اگر boolean است
    if (typeof value === 'boolean') {
        return value ? 'true' : 'false';
    }
    
    return JSON.stringify(value);
}

function formatEVMStyleValue(styleApi, value) {
    if (value === undefined || value === null || value === '') {
        return '0';
    }
    
    // اگر رشته است
    if (typeof value === 'string') {
        let cleanValue = value;
        if (cleanValue.startsWith('"') && cleanValue.endsWith('"')) {
            cleanValue = cleanValue.slice(1, -1);
        }
        if (cleanValue.startsWith("'") && cleanValue.endsWith("'")) {
            cleanValue = cleanValue.slice(1, -1);
        }
        
        // برای رنگ‌ها
        if (styleApi.includes('color')) {
            if (cleanValue.startsWith('0x')) {
                return `lv.lv_color_hex(${cleanValue})`;
            }
            if (cleanValue.startsWith('#')) {
                const hex = cleanValue.replace('#', '0x');
                return `lv.lv_color_hex(${hex})`;
            }
            // اگر عدد است
            if (!isNaN(cleanValue)) {
                return `lv.lv_color_hex(0x${parseInt(cleanValue).toString(16).padStart(6, '0')})`;
            }
        }
        
        // برای opa
        if (styleApi.includes('opa')) {
            if (cleanValue === '255' || cleanValue.toLowerCase() === 'cover' || cleanValue.toLowerCase() === 'lv_opa_cover') {
                return '255';
            }
            if (cleanValue === '0' || cleanValue.toLowerCase() === 'transp' || cleanValue.toLowerCase() === 'lv_opa_transp') {
                return '0';
            }
        }
        
        // برای boolean (با حروف کوچک)
        if (cleanValue.toLowerCase() === 'false') return 'false';
        if (cleanValue.toLowerCase() === 'true') return 'true';
        
        // برای اعداد
        if (!isNaN(cleanValue) && cleanValue.trim() !== '') {
            return cleanValue;
        }
        
        return `"${cleanValue}"`;
    }
    
    // اگر عدد است
    if (typeof value === 'number') {
        if (styleApi.includes('color')) {
            return `lv.lv_color_hex(0x${value.toString(16).padStart(6, '0')})`;
        }
        return value;
    }
    
    // اگر boolean است
    if (typeof value === 'boolean') {
        return value ? 'true' : 'false';
    }
    
    return JSON.stringify(value);
}